version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: farmplot-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-farmplot}
      POSTGRES_USER: ${POSTGRES_USER:-farmplot_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-farmplot_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-farmplot_user} -d ${POSTGRES_DB:-farmplot}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/farmplot-backend:latest
    container_name: farmplot-backend
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${BACKEND_PORT:-5000}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-farmplot}
      POSTGRES_USER: ${POSTGRES_USER:-farmplot_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-farmplot_password}
      POSTGRES_SSL: ${POSTGRES_SSL:-false}
      ALERT_EMAIL_ENABLED: ${ALERT_EMAIL_ENABLED:-false}
      SMTP_HOST: ${SMTP_HOST:-}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASS: ${SMTP_PASS:-}
      SENDER_EMAIL: ${SENDER_EMAIL:-}
      ALERT_EMAIL_RECIPIENTS: ${ALERT_EMAIL_RECIPIENTS:-}
      ALERT_WEBHOOK_ENABLED: ${ALERT_WEBHOOK_ENABLED:-false}
      ALERT_WEBHOOK_URL: ${ALERT_WEBHOOK_URL:-}
      ALERT_WEBHOOK_API_KEY: ${ALERT_WEBHOOK_API_KEY:-}
      ALERT_WEBHOOK_TIMEOUT: ${ALERT_WEBHOOK_TIMEOUT:-10000}
      ALERT_WEBHOOK_RETRIES: ${ALERT_WEBHOOK_RETRIES:-3}
      ALERT_ESCALATION_ENABLED: ${ALERT_ESCALATION_ENABLED:-false}
    ports:
      - "${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./core/logs:/app/logs
    restart: unless-stopped

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/farmplot-frontend:latest
    container_name: farmplot-frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5000/v1}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
    name: farmplot_postgres_data
